training:
  prefix: laptop
  N_epochs: 2
  lr: 0.001
  batch_size: 3
  train_size: 12
  test_size: 12
data:
  sr: 10000
  gender: both
  vowels: 
    - ei
    - iy
    - oa
geom:
  use_design_region: true
  use_rand_init: false
  Nx: 160
  Ny: 160
  dt: 0.707
  c0: 1.0
  c1: 0.9
  px: 
  py: 
  pd: 30
  src_x: 
  src_y:
  pml:
    N: 20
    p: 4.0
    max: 3.0
  nonlinearity:
    b0: 0.0
    uth: 1.0
  binarization:
    beta: 100
    eta: 0.5
