training:
  prefix: prod_vow3
  N_epochs: 20
  lr: 0.0001
  batch_size: 9
  train_size: 90
  test_size: 45
data:
  sr: 10000
  gender: both
  vowels: 
    - ei
    - iy
    - oa
geom:
  use_design_region: true
  use_rand_init: false
  Nx: 220
  Ny: 180
  dt: 0.707
  c0: 1.00
  c1: 0.85
  px: 
  py: 
  pd: 40
  src_x: 
  src_y:
  pml:
    N: 20
    p: 4.0
    max: 3.0
  nonlinearity:
    b0: 0.0
    uth: 1.0
  binarization:
    beta: 100
    eta: 0.5
