training:
  prefix: kerr
  N_epochs: 20
  lr: 0.001
  batch_size: 15
  max_samples: 
  train_test_divide: 5
  use_cross_validation: true
data:
  window_size: 1000
  sr: 10000
  gender: both
  vowels: 
    - ae
    - ei
    - iy
geom:
  use_design_region: true
  use_rand_init: false
  Nx: 140
  Ny: 100
  dt: 0.707
  h:  
  c0: 1.00
  c1: 0.75
  px: 
  py: 
  pd: 20
  src_x: 
  src_y:
  pml:
    N: 20
    p: 4.0
    max: 3.0
  nonlinearity:
    cnl: -0.3
    b0: 0.0
    uth: 0.0
  binarization:
    beta: 100
    eta: 0.5
