training:
  prefix: real
  N_epochs: 20
  lr: 0.0004
  batch_size: 9
  max_samples: 
  train_test_divide: 5
  use_cross_validation: true
data:
  window_size: 1000
  sr: 10000
  gender: both
  vowels: 
    - ae
    - ei
    - iy
geom:
  use_design_region: true
  use_rand_init: false
  Nx: 140
  Ny: 140
  dt: 0.0001
  h:  0.05
  c0: 331
  c1: 150
  px: 
  py: 
  pd: 35
  src_x: 
  src_y:
  pml:
    N: 20
    p: 4.0
    max: 10000
  nonlinearity:
    cnl: 0.0
    b0: 0.0
    uth: 0.0
  binarization:
    beta: 100
    eta: 0.5
