general:
  # Set a random seed if you want
  rand_seed: 2019
training:
  # This prefix is applied to the filename when saving the model; if not specified a date/time is used
  prefix: laptop_rnn
  # Number of training epochs
  N_epochs: 100
  # Optimizer learning rate
  lr: 0.0001    
  # Batch size     
  batch_size: 9
  # Size of randomly selected training set. Ideally, this should be a multiple of the number of vowel casses
  train_size: 90
  # Size of randomly selected testing set. Ideally, this should be a multiple of the number of vowel casses
  test_size: 30
  # Display the test/train accuracy every display_step epochs
  display_step: 10
data:
  # Sampling rate to use for vowel data
  sr: 10000       
  # Which gender to pull vowel data from. Can be one of women, men, or both. 
  # If both, training and testing datasets distributed equally over the genders
  gender: both
  # Which vowel classes to train on.
  # Can be any elements from the set: [ae, eh, ih, oo, ah, ei, iy, uh, aw, er, oa, uw].
  vowels: 
    - ae
    - ei
    - iy
rnn:
  # Hidden state size of the RNN
  N_hidden: 100
  # Hidden-to-hidden activation function, can be anything from torch.nn.functional, 
  # e.g. relu, leaky_relu or logsigmoid, or None for linear
  f_hidden: leaky_relu
  # Scale for initializing the W-matrices
  W_scale: 0.2
  # L2 regularization 
  L2_reg: 0.0001 
  # Gradient clipping. Maximum absolute value of the gradient, or None
  grad_clip: 2
